id: 1d88aaf778164d5da36eb7dc41d29f2e
initial_creation_type: ebook
source_metadata:
  title: test
  subtitle: test
  authors:
  - test
  collection: test
  publisher: test
  id: test
  cover: tmpa9pbgmn7.jpg
  credit: tmpm18vwjmz.jpg
